[colors]
background = ${xrdb:color0:#222}
foreground = ${xrdb:color7:#222}
foreground-alt = ${xrdb:color7:#222}
primary = ${xrdb:color1:#222}
secondary = ${xrdb:color2:#222}
alert = ${xrdb:color3:#222}
[bar/bar]
monitor = HDMI-A-0
width = 100%
height = 14pt
radius = 8
fixed-center = true
background = ${colors.background}
foreground = ${colors.foreground}
line-size = 1pt
border-size = 0pt
border-color = ${colors.foreground}
padding-left = 0
padding-right = 0
module-margin = 1
separator = "|"
separator-foreground = ${colors.secondary}
font-0 = "monospace:size=12;3"
font-1 = monospace;2
font-2 = "Spacemono Nerd Font:size=12;2"
font-3 = "Symbols Nerd Font:size=20;4"
modules-left =  ewmh
modules-center = date
modules-right = tray
enable-ipc = true

; Host where mpd is running (either ip or domain name)
; Can also be the full path to a unix socket where mpd is running.
[module/mpd]
host = 127.0.0.1
port = 6600
password = None

; Seconds to sleep between progressbar/song timer sync
; Default: 1
interval = 1

[module/ewmh]
type = internal/xworkspaces
icon-0 = 1;term
icon-1 = 2;browser
icon-2 = 3;anki
icon-3 = 4;
icon-4 = 5;
icon-5 = 6;
icon-6 = 7;
icon-7 = 8;
icon-8 = 9;
icon-9 = 10;
format = <label-state>
format-font = 1
#group-by-monitor = false
#pin-workspaces = false
label-active = %icon%
label-active-background = ${colors.background}
label-active-forground = #00000000
label-active-padding = 2
label-occupied = %icon%
label-occupied-padding = 1
label-urgent = %icon%
label-urgent-background = ${colors.primary}
label-urgent-padding = 1
label-empty = %icon%
label-empty-foreground = ${colors.foreground}
label-empty-padding = 1

[module/date]
type = internal/date
interval = 1.0
time = %I:%M %p
date = %d-%m-%Y
date-alt = "%{F#FF9535}%Y-%m-%d %I:%M:%S %p%{F-}"
label = %date% %time%
label-font = 1
label-foreground = ${colors.foreground}
format = 󱑂 <label>
format-prefix-font = 2

[module/tray]
type = internal/tray

format-margin = 8px
tray-spacing = 8px
